stages:          # List of stages for jobs, and their order of execution
  - build
  - unit-test
  - integrational-test
  
  
# frontend-build:
#   tags:
#   - docker-executor
#   image: node:lts-alpine
#   stage: build
#   before_script:
#     - cd ProjectSource/RedoCode_frontend
#     - yarn
#   script:
#     - npm run build-only


# backend-build:
#   tags:
#   - docker-executor
#   image: maven
#   stage: build
#   before_script:
#     - cd ProjectSource/RedoCode_backend
#   script:
#     - mvn clean install -DskipTests 


# vue-vitest:
#   tags:
#   - docker-executor 
#   image: node:20
#   stage: unit-test 
#   coverage: '/% Coverage report from v8/'
#   before_script:
#     - ls
#     - cd ProjectSource/RedoCode_frontend
#     - yarn
#   script:
#    - npm run test:dev:unit


# vue-cypress-dev:
#   tags:
#   - docker-executor 
#   image: cypress/included
#   stage: unit-test 
#   coverage: '/% Coverage report from v8/'
#   before_script:
#     - ls
#     - cd ProjectSource/RedoCode_frontend
#     - yarn
    
#   script:
#     - npm run test:dev:e2e

backend-junit-dev-docker:
  tags:
    - docker-executor
  image: docker
  # variables:
    # DOCKER_HOST: tcp://docker:2375
    # DOCKER_TLS_CERTDIR: ""
    # DOCKER_DRIVER: overlay2
  stage: unit-test 
  # before_script:
  #   - cd ProjectSource
  #   - docker-compose -f docker-compose-dev.yml up -d   
    
  script:
    # -  docker exec -it  projectsource-api-1 mvn clean install
    - docker info



# vue-cypress-prod:
#   tags:
#     - docker-executor
#   image: docker
#   stage: integrational-test
#   variables:
#     DOCKER_HOST: tcp://docker:2375
#     DOCKER_TLS_CERTDIR: ""
#     DOCKER_DRIVER: overlay2
#   before_script:
#     - cd ProjectSource
#     - apk update
#     - apk add --update npm
#     - apk add libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
#     - cd RedoCode_frontend
#     - npm install --save-dev cypress
#     - cd ../
#     - docker-compose up 
#     - cd RedoCode_frontend
    
#   script:
#     -  npm run test:prod:e2e




