stages:          # List of stages for jobs, and their order of execution
  - build
  - unit-test
  
  
frontend-build:
  tags:
  - docker-executor
  image: node:lts-alpine
  stage: build
  before_script:
    - cd ProjectSource/RedoCode_frontend
    - yarn
  script:
    - npm run build-only


backend-build:
  tags:
  - docker-executor
  image: maven
  stage: build
  before_script:
    - cd ProjectSource/RedoCode_backend
  script:
    - mvn clean install -DskipTests 


vue-vitest:
  tags:
  - docker-executor 
  image: node:20
  stage: unit-test 
  coverage: '/% Coverage report from v8/'
  before_script:
    - ls
    - cd ProjectSource/RedoCode_frontend
    - yarn
  script:
   - npm run test:dev:unit


vue-cypress-dev:
  tags:
  - docker-executor 
  image: node:20
  stage: unit-test 
  coverage: '/% Coverage report from v8/'
  before_script:
    - ls
    - cd ProjectSource/RedoCode_frontend
    - yarn
    
  script:
   - npm run test:dev:e2e

backend-junit-dev-docker:
  tags:
    - docker-executor
  image: docker
  
  variables:
    POSTGRES_DB: RedoCode-database
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    CONTAINER_MANGER: docker
  stage: unit-test 
  before_script:
    - apt update -y
    - apt-get update -qy
    - apt-get install wget -y  
    - apt install default-jre -y
    - java -version
    - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
    - tar -xvf apache-maven-3.9.6-bin.tar.gz
    - mv  apache-maven-3.9.6 /opt/
    - M2_HOME='/opt/apache-maven-3.9.6'
    - PATH="$M2_HOME/bin:$PATH"
    - export PATH
    
  script:
   - mvn -v
   - export PGPASSWORD=$POSTGRES_PASSWORD
   - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
   - cd ProjectSource/RedoCode_backend
   - mvn test 



