stages:          # List of stages for jobs, and their order of execution
  - build
  - unit-test
  - integrational-test
  
  
frontend-build:
  tags:
  - docker-executor
  image: node:lts-alpine
  stage: build
  before_script:
    - cd ProjectSource/RedoCode_frontend
    - yarn
  script:
    - npm run build-only


backend-build:
  tags:
  - docker-executor
  image: maven
  stage: build
  before_script:
    - cd ProjectSource/RedoCode_backend
  script:
    - mvn clean install -DskipTests 


vue-vitest:
  tags:
  - docker-executor 
  image: node:20
  stage: unit-test 
  coverage: '/% Coverage report from v8/'
  before_script:
    - ls
    - cd ProjectSource/RedoCode_frontend
    - yarn
  script:
   - npm run test:dev:unit


vue-cypress-dev:
  tags:
  - docker-executor 
  image: node:20
  stage: unit-test 
  coverage: '/% Coverage report from v8/'
  before_script:
    - ls
    - cd ProjectSource/RedoCode_frontend
    - yarn
    
  script:
    - npm run test:dev:e2e

backend-junit-dev-docker:
  tags:
    - docker-executor
  image: docker:18.0.1-dind
  stage: unit-test 
  before_script:
    - cd ProjectSource
    - docker compose -f docker-compose-dev.yml up -d   
    
  script:
    -  docker exec -it  projectsource-api-1 mvn clean install



backend-junit-prod-docker:
  tags:
    - docker-executor
  image: docker:18.0.1-dind
  stage: integrational-test
  before_script:
    - cd ProjectSource
    - apt update
    - apt install npm
    - apt install cypress
    - docker compose up -d
    - cd RedoCode_frontend
    
  script:
    -  npm run test:prod:e2e




