stages:          # List of stages for jobs, and their order of execution
  - test

test-job:
  tags:
  - docker-executor 
  image: node:20
  stage: test 
  coverage: '/% Coverage report from v8/'
  before_script:
    - ls
    - cd ProjectSource/coding_exercise_frontend
    - npm install
    - yarn
    
  script:
   - yarn vitest run --coverage



