stages:          # List of stages for jobs, and their order of execution
  - test

test-job:
  tags:
  - docker-executor 
  image: node:20
  stage: test 
  coverage: '/% Coverage report from v8/'
  before_script:
    - ls
    - cd ProjectSource/RedoCode_frontend
    - npm install
    
  script:
   - npx vitest run --coverage



