name: code-formatting

on:
  push:
    branches:
      - main
jobs:
  formatting-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"

  prettier:
    needs:
      - formatting-java
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write "**/*.{js,ts,vue,json,md,css,scss,html}"
      - name: Commit and Push Changes (Prettier)
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git pull --rebase origin main
          git add -A
          git commit -m "Prettier code formatting"
          git push origin ${{ github.ref }}
