name: code-formatting

on:
  push

jobs:
  format-java-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: prettier-java-format-action
      uses: tsar-boomba/prettier-java-action@v1.1.0
      with:
        prettier-args: '--tab-width 4  --write'
        files: '**/*.java'
        commit: 'true'
        github-username: 'github-actions'
        commit-message: 'Format Java Code'

            