name: code-formatting

on:
  push

jobs:
  reformat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: joutvhu/intellij-format@v1
        with:
          path: './ProjectSource/RedoCode_backend'
          mask: '**/*.java

            